name: C++ Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Скачивание кода репозитория
      uses: actions/checkout@v4

    - name: Настройка NuGet
      uses: nuget/setup-nuget@v2

    - name: Восстановление NuGet-пакетов
      run: nuget restore AnalyzesSpecrtum/AnalyzesSpecrtum.vcxproj -PackagesDirectory AnalyzesSpecrtum/packages

    - name: Настройка MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Сборка проекта
      run: msbuild AnalyzesSpecrtum/AnalyzesSpecrtum.vcxproj /p:Configuration=Debug /p:Platform=x64
