name: C++ Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Скачивание кода репозитория
      uses: actions/checkout@v4

    - name: Настройка MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Установка и настройка NuGet
      uses: NuGet/setup-nuget@v3.0.0

    - name: Восстановление NuGet-пакетов

      run: nuget restore AnalyzesSpecrtum.vcxproj -PackagesDirectory packages

- name: Сборка проекта
      run: msbuild AnalyzesSpecrtum.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:PlatformToolset=v143
